### ISSUE TITLE
_make_ax_ref not defined

### ISSUE THREAD

**Issue by scdhulipala** [NREL-Sienna/PowerNetworkMatrices.jl#88] opened 2024-09-19 20:19 UTC
When trying to run _find_connected_components_ on a PSY-3.X System, `sub_networks = PNM.find_connected_components(ladwp_sys);`, I get the following error:

ERROR: UndefVarError: `_make_ax_ref` not defined
Stacktrace:
 [1] PowerNetworkMatrices.Adjacency(branches::InfrastructureSystems.FlattenIteratorWrapper{Branch, Vector{Base.ValueIterator}}, nodes::Vector{ACBus}; check_connectivity::Bool, kwargs::@Kwargs{})
   @ PowerNetworkMatrices ~/.conda-envs/sdhulipa-julia1.10.3/share/julia/packages/PowerNetworkMatrices/YBcAg/src/ybus_calculations.jl:230
 [2] PowerNetworkMatrices.Adjacency(sys::System; check_connectivity::Bool, kwargs::@Kwargs{})
   @ PowerNetworkMatrices ~/.conda-envs/sdhulipa-julia1.10.3/share/julia/packages/PowerNetworkMatrices/YBcAg/src/ybus_calculations.jl:270
 [3] Adjacency
   @ ~/.conda-envs/sdhulipa-julia1.10.3/share/julia/packages/PowerNetworkMatrices/YBcAg/src/ybus_calculations.jl:258 [inlined]
 [4] find_connected_components(sys::System)
   @ PowerNetworkMatrices ~/.conda-envs/sdhulipa-julia1.10.3/share/julia/packages/PowerNetworkMatrices/YBcAg/src/ybus_calculations.jl:339
 [5] top-level scope
   @ REPL[91]:1

**Comment by jd-lara** [comment] 2024-09-21 02:12
close as a duplicate of #86

**Closed by jd-lara** 2024-09-21 02:12 UTC
